package com.sumit.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@DynamoDBTable(tableName = "Employee")
public class Employee {

	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
    private String id;

	@DynamoDBAttribute
    private String employeeName;

	@DynamoDBAttribute
    private float employeeSalary;

    public Employee() {
    }

    public Employee(String employeeId, String employeeName, float employeeSalary) {
        this.id = employeeId;
        this.employeeName = employeeName;
        this.employeeSalary = employeeSalary;
    }

    public Employee( String employeeName, float employeeSalary) {
        this.employeeName = employeeName;
        this.employeeSalary = employeeSalary;
    }
}
